spring.application.name=bancocn



spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=luiz
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

// visualizar o console h2
spring.h2.console.enabled=true
